server:
  port: 9001

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: api-patient
              uri: lb://patient-service
              predicates:
                - Path=/api/patients, /api/patients/, /api/patients/**
              filters:
                - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9004/eureka/